#!/bin/sh
s="$1"; shift
i="$1"; shift
name=`basename $0`
if test ! -n "$i"; then
  case "$s" in
    *.sh) i=sh;;
    *.pl) i=perl;;
    *) echo >&2 "usage: $name <scriptname> <interpreter>"; exit 1;;
  esac
fi
i=`which $i`
echo "#!$i $@" > $s
chmod +x $s
