#!/usr/bin/env perl

# Generate an SVN annotation of a local version of a file.

sub Trace(@);
$trace = 0;

while ($ARGV[0] =~ /^-/) {
  $arg = shift @ARGV;
  $trace++ if $arg eq "-t";
  open STDERR, ">&STDOUT" if $arg eq "-o";
}

$prefix = "locally modified: ";

foreach $file (@ARGV) {
  $status = `svn status -v $file`;
  $rev = (split(" ", substr($status,8)))[0];
  open DIFF, "svn diff -r$rev $file |";
  $d = <DIFF>; # cause something to happen to this
  open ANNOTATE, "svn blame -r$rev $file |";

  $inline = $outline = 1;
  while (1) {
    # Find a diff in file DIFF.
    while ($d) {
      chomp $d;
      $line=$1, last if $d =~ /^@@ -(\d+),\d+ \+\d+,\d+ @@$/;
      $d = <DIFF>;
    }
    Trace "--- Diff is :$d:\n";
    last if !defined $d;  # end of diffs
    # We're now holding the line that starts a unidiff section,
    # which is of the format `@@ -1403,67 +1403,121 @@'. The first
    # of those four numbers is the input line at which the diff
    # section begins.
    Trace "Reading up to inline $line (now $inline)\n";
    $inline++, $outline++, $_ = <ANNOTATE>, print $_ while $inline < $line;
    Trace "Got there\n";
    # Now we read lines from the unidiff. Each one begins with
    # either a space (meaning we copy a line from ANNOTATE to
    # output), a minus (meaning we skip a line from ANNOTATE), or a
    # plus (meaning we print the rest of the line from DIFF).
    while (1) {
      $d = <DIFF>;
      $c = substr($d, 0, 1);
      if ($c eq " ") {
	$inline++, $outline++, $_ = <ANNOTATE>, print $_;
      } elsif ($c eq "-") {
	$inline++, $_ = <ANNOTATE>;
      } elsif ($c eq "+") {
	$outline++, print $prefix, substr($d, 1);
      } else {
        last;
      }
    }
  }
  # We're out of diffs; spew the rest of the annotation.
  close DIFF;
  print while <ANNOTATE>;
  close ANNOTATE;
}

sub Trace(@) {
  print STDERR @_ if $trace;
}
