#!/bin/sh 

# Wrapper on `svn log' that does what I usually want.

case "$1" in
  -r*) dashr="$1"; shift;;
  *) dashr=-rHEAD:1;;
esac

uuid=`svn info "$1" | tr -d '\r' | grep '^Repository UUID:' | cut -f3- -d' '`

svn log -v $dashr "$@" | \
  perl -e '

$uuid = shift @ARGV;
while (<>) {
    y/\r//d;
    print;
    next unless /^r(\d+).*(\d+) lines?$/;
    ($rev,$lines) = ($1,$2);
    # Now parsing a revision record. Omit the changed paths section
    # if it is going to be a problematic one.
    if (($uuid eq "cda61777-01e9-0310-a592-d414129be87e" and
         ($rev eq "4787" or $rev eq "4788" or $rev eq "4813")) or
        ($uuid eq "07687609-9ffd-0310-b3d8-e1e92c021e09" and
         ($rev eq "91719" or $rev eq "91739" or
          $rev eq "91768" or $rev eq "91721"))) {
	print "[svnlog: changed paths section omitted]\n\n";
	while (<>) {
            y/\r//d;
            chomp;
	    last unless length $_ > 0;
	}
    } else {
        # Print the changed paths section as normal.
	while (<>) {
            y/\r//d;
	    print;
	    chomp;
	    last unless length $_ > 0;
	}
    }
    # Now we have read and printed the blank line coming before the
    # log message. Now print $lines lines of log.
    while ($lines-- > 0) {
        $_ = <>;
        y/\r//d;
        print;
    }
}

' $uuid
