#!/bin/sh

# Switch over to my USB wired ethernet dongle, since I don't want
# to have to run wi-fi in my home just for the Chumby.
insmod /drivers/usbnet.ko
insmod /drivers/pegasus.ko
udhcpc -t 5 -n -p /var/run/udhcpc.eth0.pid -i eth0
ifconfig rausb0 down

if test -f /mnt/usb/sshkeys; then
  # Enable sshd, but first lock down the passwordless default
  # accounts. For some reason the Chumby sshd doesn't like password
  # authentication at all, so we must also provide some public
  # keys.
  perl -pe 's/^([^:]*)::/$1:*:/' /etc/shadow > /tmp/shadow
  mount --bind /tmp/shadow /etc/shadow
  (umask 077;
   mkdir /tmp/root.ssh;
   cat /mnt/usb/sshkeys > /tmp/root.ssh/authorized_keys)
  mount --bind /tmp/root.ssh ~root/.ssh
  /sbin/sshd
fi

# This process seems to spend most of its time repeatedly making
# the same HTTP request to www.chumby.com . DO NOT WANT.
killall headphone_mgr

/usr/chumby/scripts/sync_time.sh

set --
if test -f /mnt/usb/excurl; then
  set -- -u "`cat /mnt/usb/excurl`"
fi

/mnt/usb/tring -f /mnt/usb/tringsettings "$@"
