#!/bin/sh
{ restricted-hours; } >&2 2>/dev/null && exit 0
FRIENDS=`sed 's/#.*$//' << EOF

westley  # Jon Skeet
larch    # Sophie Tatham
agrajag evilmike  # Michael Nonweiler
pteppic  # Clive Ponsonby
bagpuss  # Alex Barnard
lenin markov nietzch waldo  # Tim Bramham
eliza    # Phil Blundell
war      # Graham Boyd
pooz     # Piers Walton
ghoti jupiter  # Kirsten Procter
cemerson llama  # Chris Emerson
jules    # Julian Hall
cassi    # Sally Riordan
dando    # Dan Curtis
khamul cain genocide  # Alden Spiess
joiner   # Kelly ???
kazmania # Karen Fletcher
ceb      # Clare Boothby
amf mimic fragment  # <+-AMF-+>
abi sparka  # Abigail Silvester
clare oopamoss  # Clare Farrar
marauder # Olivia Patterson
silence hiccup yourself slimy sliiiemy i lanark  # Alison Farmer
catbells # Dave Hinton
crown    # Jules Hill
bjh      # Ben Harris
fiddler  # Sabrina
matyjo   # Mary Argent
fredlegs # Hairy Matt
vicky    # Vicky Sloane
blaknail # Ben Parker
gawl     # Graham Lovell
etoile   # Yasmin Lentin
loony    # Emily Knight
kilinrax # Alex Bowley
cavalr-2 # David Damerell
valkyrie # Karen Boyd
fumble   # Jacob Nevins
arcman   # Alex Seeley
obo ezekiel weirdo oo ee  # Gareth Taylor
steph nding  # Owen Dunn
cowe scarey  # Brian Cowe
lizard   # Clare Izard
raedwald # Jon Jarrett
scruple  # Emily Cox
dj       # James Aylett
eek      # Eek the Bat
sherbet  # Sherbet the Sheep
garycook # Gary Cook
heifere  # Alison Cowe
desade marquis nine  # Oliver-Michael Longden
rjk      # Richard Kettlewell
gothbabe # Liz Chapman
julibaby # Juliet Ehimuan
rathenar # Kit Scorah
kallisti # Matt Marcus
claire   # Claire Lawson
eviltwin # Emma Bennett
lark serenity spodness geekness  # Vicky Clarke
elise    # Elisabeth Conolly
songster # Peter Ellis
sphyg    # Lucy McWilliam
neofelis # Mary Chester-Kadwell

arkady   # Eva Myers
mormegil # Martin Read

EOF
`
ME='anakin narg golem'
if test "$1" = "-f"; then f=-f; else f=; fi
mfinger $f $FRIENDS $ME
