#!/bin/sh
FRIENDS=`cat << EOF

westley larch agrajag pteppic bagpuss robin lenin eliza war pooz ghoti cemerson
jules cassi dando nietzch khamul kazmania ceb mimic abi clare quirka amf markov
marauder hiccup catbells crown bjh fiddler golem oopamoss matyjo fredlegs vicky
harker waldo blaknail gawl etoile loony kilinrax cavalr-2 valkyrie fleeg fumble
arcman weirdo steph scarey silence lizard richard raedwald batboy jinxx scruple
dj cowe obo eek ezekiel sherbet garycook nding heifere fragment yourself desade
o jupiter rjk cain genocide wasp gothbabe dead slimy sliiiemy i julibaby sparka
oo ee rathenar kallisti claire lanark eviltwin lark llama

arkady mormegil

EOF
`
ME='anakin narg'
mfinger $FRIENDS $ME
