#!/bin/sh
FRIENDS=`cat << EOF

westley larch agrajag pteppic bagpuss robin lenin eliza war pooz ghoti cemerson
jules cassi dando nietzch khamul kazmania ceb mimic abi clare quirka amf markov
marauder hiccup catbells crown bjh fiddler golem oopamoss matyjo fredlegs vicky
harker waldo blaknail gawl etoile loony kilinrax cavalr-2 valkyrie fleeg fumble
arcman weirdo steph scarey silence lizard richard raedwald batboy jinxx scruple
dj cowe obo ee ezekiel sherbet garycook madprof nding heifere fragment yourself
o jupiter rjk cain genocide wasp gothbabe dead slimy sliiiemy i julibaby sparka
oo rathenar kallisti claire lanark

arkady mormegil

EOF
`
mfinger |
  perl -e 'foreach $i (@ARGV) {$q{$i}=1;} while (<STDIN>) {' \
       -e 'print if (/^.([a-z0-9_\-]+)/ and $q{$1}) or /^\d+ users/ }' $FRIENDS
