#!/bin/sh

# cmdline arguments
finger=no
done=no
while test $# -gt 0 -a "$done" != "yes"; do
  case $1 in
    -f) finger=yes; shift;;
    -*) echo "Unknown option $1" >&2; shift;;
    *) done=yes
  esac
done

# output width
getwidth() {
  set -- `stty 2>/dev/null | tr -s ';\n' '\n\n' | grep columns`
  cols=${3-80}
}
getwidth   # it's a function so as not to trash $*

# do the job
{
 if test $finger = no; then
  location=http://mono.org/newweb/utils/users_on.shtml
  perl -e "use LWP::Simple; print get('$location')" |
    perl -n -e '%cmap=("black"=>"K","blue"=>"B","green"=>"G","red"=>"R",' \
         -e '"cyan"=>"C","magenta"=>"M","yellow"=>"Y","white"=>"W",""=>"A");' \
         -e 'if (/^<PRE>/) { $p=1 } elsif (/^<\/PRE/) { $p=0 } elsif ($p) {' \
         -e '  s/<A ("[^"]*"|[^">])*>//g; s/<\/A>//g;' \
         -e '  s/<FONT COLOR="([^"]*)">/"\035C".$cmap{$1}/eg;' \
         -e '  s/<\/FONT>/\035CA/g;' \
         -e '  s/<STRONG>/\035B/g;' \
         -e '  s/<\/STRONG>/\035b/g;' \
         -e '  s/<EM>/\035S/g;' \
         -e '  s/<\/EM>/\035s/g;' \
         -e '  s/<U>/\035U/g;' \
         -e '  s/<\/U>/\035u/g;' \
         -e '  print }'
 else
   finger userson@mono.org |
     perl -ne 's/\^\[/\033/g, s/\^\]/\035/g, print if $ok; $ok=1 if /^Plan:/'
 fi
} | mtribs -b49 -s`expr $cols - 1` | {
  if test $# -gt 0; then
    perl -e 'foreach $i (@ARGV) {$q{$i}=1;} while (<STDIN>) {' \
         -e 'print if (/^.([a-z0-9_\-]+)/ and $q{$1}) or /^\d+ users/ }' "$@"
  else
    cat
  fi
}
