#!/bin/sh

# Report the playback duration of a movie file.

for file in "$@"; do
  LENGTH=`mplayer -vo null -ao null -frames 0 -identify "$file" 2>&1 | \
          perl -ne '/^ID_LENGTH=(.*)$/ and print "$1\n"'`
  perl -e 'printf "%s: %g sec (%d:%02d)\n", $ARGV[0], $ARGV[1], ' \
       -e 'int($ARGV[1])/60, int($ARGV[1])%60' "$file" "$LENGTH"
done
