#!/bin/sh

name=`basename $0` # for usage message

# First parameter is the name of the new script
if test $# -gt 0; then
  s="$1"; shift
else
  echo >&2 "usage: $name <scriptname> [<interpreter>]"; exit 1
fi

# Optional second parameter is the name of the interpreter
if test $# -gt 0; then
  i="$1"; shift
else
  case "$s" in
    *.sh) i=sh;;
    *.pl) i=perl;;
    *.py) i=env; set python "$@";;
    *) echo >&2 "usage: $name <scriptname> [<interpreter>]"; exit 1;;
  esac
fi
i=`which $i`

set -- "#!$i" "$@"
/bin/echo "$@" > $s
chmod +x $s
