#!/usr/bin/env python

# import urlparse
import string
import sys

url = sys.argv[1]

try:
    from urlrewritelocal import local_rewrite
except ImportError:
    def local_rewrite(url):
        pass

local_rewrite(url) # will exit on success

if url[-16:] == "@bugs.debian.org":
    # Rewrite <number>@bugs.debian.org into a URL in the Debian BTS.
    if url[:7] == "http://":
        url = url[7:]
    number = url[:-16] # strip off the host part
    index = string.find(number, "-")
    if index >= 0:
        number = number[:index] # strip off "-forwarded" or similar
    print "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=" + number
    sys.exit(0)

# The following rewrite rules are obsolete because ick-proxy does
# the same job better. The code is preserved in case I need to do
# other similar rewrites in future.
#
# t = urlparse.urlparse(url)
#
# if t[0] == "http" and t[1] == "www.livejournal.com" and \
# (t[2][:7] == "/users/" or t[2][:11] == "/community/"):
#     # For any link which deals in someone's actual journal, we want
#     # to ensure `style=mine' is one of the query variables if there
#     # isn't already a style setting.
#     #
#     # Oh, except that _my_ journal is exempt!
#     if t[2][:14] != "/users/simont/":
#         if t[4] == "":
#             queries = []
#         else:
#             queries = string.split(t[4], "&")
#         found=0
#         for s in queries:
#             if s[:6] == "style=":
#                 found=1
#                 break
#         if not found:
#             queries = queries + ["style=mine"]
#             tl = list(t)
#             tl[4] = string.join(queries, "&")
#             t = tuple(tl)
#             print urlparse.urlunparse(t)
#
# if t[0] == "http" and t[1] == "lists.tartarus.org":
#     t = t[:1] + ("tunnel.lists.tartarus.org",) + t[2:]
#     print urlparse.urlunparse(t)
