#!/usr/bin/env python

import sha
import sys
import socket
import string

debug = 0

server = sys.argv[1]
secretfile = sys.argv[2]
cmd = sys.argv[3]

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(server, 17481)
sf = s.makefile("r")

greet = sf.readline()
if debug: sys.stderr.write("<<< "+greet)

nonce = greet[1:string.find(greet, "\r")]

shaobj = sha.new()
shaobj.update(nonce)
shaobj.update(open(secretfile, "rb").read())
shaobj.update(cmd)
auth = shaobj.hexdigest()

ourline = auth + cmd + "\r\n"
s.send(ourline)
if debug: sys.stderr.write(">>> "+ourline)

status = sf.readline()
if debug: sys.stderr.write("<<< "+status)
while status[:1] == "=":
    b = ""
    h = status[1:string.find(status, "\r")]
    while len(h) >= 2:
        b = b + chr(string.atoi(h[0:2], 16))
        h = h[2:]
    sys.stdout.write(b)
    status = sf.readline()
    if debug: sys.stderr.write("<<< "+status)

sys.stdout.flush()

if status[:1] != "+":
    if status == "":
        sys.stderr.write("connection closed unexpectedly")
    else:
        sys.stderr.write("error: " + status)
    sys.exit(1)

sys.exit(0)
