all: face2a.png face3a.png face4a.png face5a.png face6a.png face7a.png \
     face8a.png face9a.png face10a.png face11a.png face12a.png \
     face2b.png face3b.png face4b.png face5b.png face6b.png face7b.png \
     face8b.png face9b.png face10b.png face11b.png face12b.png \
     faceblank.png rhead.png chead.png tblhead.png \
     tblcol1.png tblcol2.png tblcol3.png tblcol4.png tblcol5.png tblcol6.png \
     tblcol7.png tblcol9.png tblcol11.png tblcolblank.png \
     tblrow1.png tblrow2.png tblrow3.png tblrow4.png tblrow5.png tblrow6.png \
     tblrow8.png tblrow10.png tblrow12.png \
     tbl2.png tbl3.png tbl4.png tbl5.png tbl6.png tbl7.png \
     tbl8.png tbl9.png tbl10.png tbl11.png tbl12.png \
     tblq.png tblqd.png tblqr.png tblqdr.png \
     tbl7d.png tbl6r.png tbl8r.png tbl5d.png tbl9d.png \
     tbl4r.png tbl10r.png tbl3d.png tbl11d.png \
     tbl2-1.png \
     tbl3-1.png tbl3-2.png \
     tbl4-1.png tbl4-2.png tbl4-3.png \
     tbl5-1.png tbl5-2.png tbl5-3.png tbl5-4.png \
     tbl6-1.png tbl6-2.png tbl6-3.png tbl6-4.png tbl6-5.png \
     tbl7-1.png tbl7-2.png tbl7-3.png tbl7-4.png tbl7-5.png tbl7-6.png \
     tbl8-2.png tbl8-3.png tbl8-4.png tbl8-5.png tbl8-6.png \
     tbl9-3.png tbl9-4.png tbl9-5.png tbl9-6.png \
     tbl10-4.png tbl10-5.png tbl10-6.png \
     tbl11-5.png tbl11-6.png \
     tbl12-6.png \
     tbl3-1d.png \
     tbl4-1r.png tbl4-2r.png \
     tbl5-1d.png tbl5-2d.png tbl5-3d.png \
     tbl6-1r.png tbl6-2r.png tbl6-3r.png tbl6-4r.png \
     tbl7-1d.png tbl7-2d.png tbl7-3d.png tbl7-4d.png tbl7-5d.png \
     tbl8-2r.png tbl8-3r.png tbl8-4r.png tbl8-5r.png \
     tbl9-3d.png tbl9-4d.png tbl9-5d.png \
     tbl10-4r.png tbl10-5r.png \
     tbl11-5d.png \
     tbl1red.png tbl2red.png tbl3red.png tbl4red.png tbl5red.png tbl6red.png \
     tbl1redr.png tbl2redr.png tbl3redr.png tbl4redr.png tbl5redr.png \
     tbl1redd.png tbl2redd.png tbl3redd.png tbl4redd.png \
     tbl5redd.png tbl6redd.png

face2a.png: face.ps
	echo '(2) 1 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face3a.png: face.ps
	echo '(3) 2 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face4a.png: face.ps
	echo '(4) 3 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face5a.png: face.ps
	echo '(5) 4 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face6a.png: face.ps
	echo '(6) 5 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face7a.png: face.ps
	echo '(7) 6 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face8a.png: face.ps
	echo '(8) 5 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face9a.png: face.ps
	echo '(9) 4 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face10a.png: face.ps
	echo '(10) 3 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face11a.png: face.ps
	echo '(11) 2 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face12a.png: face.ps
	echo '(12) 1 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face2b.png: face.ps
	echo '(2) 1 (1)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face3b.png: face.ps
	echo '(3) 2 (+1)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face4b.png: face.ps
	echo '(4) 3 (2)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face5b.png: face.ps
	echo '(5) 4 (+2)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face6b.png: face.ps
	echo '(6) 5 (3)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face7b.png: face.ps
	echo '(7) 6 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face8b.png: face.ps
	echo '(8) 5 (4)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face9b.png: face.ps
	echo '(9) 4 (-2)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face10b.png: face.ps
	echo '(10) 3 (5)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face11b.png: face.ps
	echo '(11) 2 (-1)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

face12b.png: face.ps
	echo '(12) 1 (6)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

faceblank.png: face.ps
	echo '() 0 ()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

rhead.png: head.ps
	echo '(R:)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

chead.png: head.ps
	echo '(C:)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 75x75 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblhead.png: tblhead.ps
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g450x450 -r216 \
		-dBATCH -dNOPAUSE -q $<
	convert -geometry 45x45 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblcol1.png: tblcolhead.ps
	echo '(1)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x450 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x45 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblcol2.png: tblcolhead.ps
	echo '(2)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x450 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x45 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblcol3.png: tblcolhead.ps
	echo '(3)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x450 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x45 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblcol4.png: tblcolhead.ps
	echo '(4)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x450 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x45 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblcol5.png: tblcolhead.ps
	echo '(5)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x450 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x45 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblcol6.png: tblcolhead.ps
	echo '(6)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x450 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x45 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblcol7.png: tblcolhead.ps
	echo '(7)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x450 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x45 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblcol9.png: tblcolhead.ps
	echo '(9)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x450 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x45 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblcol11.png: tblcolhead.ps
	echo '(11)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x450 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x45 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblcolblank.png: tblcolhead.ps
	echo '()' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x450 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x45 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblrow1.png: tblrowhead.ps
	echo '(1)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g450x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 45x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblrow2.png: tblrowhead.ps
	echo '(2)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g450x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 45x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblrow3.png: tblrowhead.ps
	echo '(3)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g450x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 45x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblrow4.png: tblrowhead.ps
	echo '(4)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g450x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 45x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblrow5.png: tblrowhead.ps
	echo '(5)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g450x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 45x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblrow6.png: tblrowhead.ps
	echo '(6)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g450x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 45x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblrow8.png: tblrowhead.ps
	echo '(8)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g450x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 45x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblrow10.png: tblrowhead.ps
	echo '(10)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g450x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 45x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblrow12.png: tblrowhead.ps
	echo '(12)' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g450x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 45x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl1.png: tblentry.ps
	echo '(1) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl2.png: tblentry.ps
	echo '(2) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl3.png: tblentry.ps
	echo '(3) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl3d.png: tblentry.ps
	echo '(3) () true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl4.png: tblentry.ps
	echo '(4) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl4r.png: tblentry.ps
	echo '(4) () false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5.png: tblentry.ps
	echo '(5) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5d.png: tblentry.ps
	echo '(5) () true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6.png: tblentry.ps
	echo '(6) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6r.png: tblentry.ps
	echo '(6) () false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7.png: tblentry.ps
	echo '(7) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7d.png: tblentry.ps
	echo '(7) () true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl8.png: tblentry.ps
	echo '(8) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl8r.png: tblentry.ps
	echo '(8) () false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl9.png: tblentry.ps
	echo '(9) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl9d.png: tblentry.ps
	echo '(9) () true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl10.png: tblentry.ps
	echo '(10) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl10r.png: tblentry.ps
	echo '(10) () false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl11.png: tblentry.ps
	echo '(11) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl11d.png: tblentry.ps
	echo '(11) () true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl12.png: tblentry.ps
	echo '(12) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblq.png: tblentry.ps
	echo '(?) () true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblqd.png: tblentry.ps
	echo '(?) () true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblqr.png: tblentry.ps
	echo '(?) () false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tblqdr.png: tblentry.ps
	echo '(?) () false false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl2-1.png: tblentry.ps
	echo '(2) (1) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl3-1.png: tblentry.ps
	echo '(3) (1) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl3-2.png: tblentry.ps
	echo '(3) (2) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl4-1.png: tblentry.ps
	echo '(4) (1) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl4-2.png: tblentry.ps
	echo '(4) (2) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl4-3.png: tblentry.ps
	echo '(4) (3) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5-1.png: tblentry.ps
	echo '(5) (1) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5-2.png: tblentry.ps
	echo '(5) (2) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5-3.png: tblentry.ps
	echo '(5) (3) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5-4.png: tblentry.ps
	echo '(5) (4) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6-1.png: tblentry.ps
	echo '(6) (1) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6-2.png: tblentry.ps
	echo '(6) (2) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6-3.png: tblentry.ps
	echo '(6) (3) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6-4.png: tblentry.ps
	echo '(6) (4) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6-5.png: tblentry.ps
	echo '(6) (5) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7-1.png: tblentry.ps
	echo '(7) (1) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7-2.png: tblentry.ps
	echo '(7) (2) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7-3.png: tblentry.ps
	echo '(7) (3) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7-4.png: tblentry.ps
	echo '(7) (4) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7-5.png: tblentry.ps
	echo '(7) (5) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7-6.png: tblentry.ps
	echo '(7) (6) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl8-2.png: tblentry.ps
	echo '(8) (2) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl8-3.png: tblentry.ps
	echo '(8) (3) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl8-4.png: tblentry.ps
	echo '(8) (4) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl8-5.png: tblentry.ps
	echo '(8) (5) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl8-6.png: tblentry.ps
	echo '(8) (6) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl9-3.png: tblentry.ps
	echo '(9) (3) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl9-4.png: tblentry.ps
	echo '(9) (4) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl9-5.png: tblentry.ps
	echo '(9) (5) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl9-6.png: tblentry.ps
	echo '(9) (6) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl10-4.png: tblentry.ps
	echo '(10) (4) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl10-5.png: tblentry.ps
	echo '(10) (5) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl10-6.png: tblentry.ps
	echo '(10) (6) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl11-5.png: tblentry.ps
	echo '(11) (5) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl11-6.png: tblentry.ps
	echo '(11) (6) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl12-6.png: tblentry.ps
	echo '(12) (6) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl3-1d.png: tblentry.ps
	echo '(3) (1) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl4-1r.png: tblentry.ps
	echo '(4) (1) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl4-2r.png: tblentry.ps
	echo '(4) (2) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5-1d.png: tblentry.ps
	echo '(5) (1) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5-2d.png: tblentry.ps
	echo '(5) (2) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5-3d.png: tblentry.ps
	echo '(5) (3) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6-1r.png: tblentry.ps
	echo '(6) (1) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6-2r.png: tblentry.ps
	echo '(6) (2) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6-3r.png: tblentry.ps
	echo '(6) (3) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6-4r.png: tblentry.ps
	echo '(6) (4) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7-1d.png: tblentry.ps
	echo '(7) (1) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7-2d.png: tblentry.ps
	echo '(7) (2) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7-3d.png: tblentry.ps
	echo '(7) (3) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7-4d.png: tblentry.ps
	echo '(7) (4) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl7-5d.png: tblentry.ps
	echo '(7) (5) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl8-2r.png: tblentry.ps
	echo '(8) (2) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl8-3r.png: tblentry.ps
	echo '(8) (3) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl8-4r.png: tblentry.ps
	echo '(8) (4) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl8-5r.png: tblentry.ps
	echo '(8) (5) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl9-3d.png: tblentry.ps
	echo '(9) (3) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl9-4d.png: tblentry.ps
	echo '(9) (4) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl9-5d.png: tblentry.ps
	echo '(9) (5) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl10-4r.png: tblentry.ps
	echo '(10) (4) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl10-5r.png: tblentry.ps
	echo '(10) (5) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl11-5d.png: tblentry.ps
	echo '(11) (5) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bm

tbl1red.png: tblredentry.ps
	echo '(1) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl2red.png: tblredentry.ps
	echo '(2) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl3red.png: tblredentry.ps
	echo '(3) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl4red.png: tblredentry.ps
	echo '(4) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5red.png: tblredentry.ps
	echo '(5) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6red.png: tblredentry.ps
	echo '(6) true true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl1redr.png: tblredentry.ps
	echo '(1) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl2redr.png: tblredentry.ps
	echo '(2) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl3redr.png: tblredentry.ps
	echo '(3) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl4redr.png: tblredentry.ps
	echo '(4) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5redr.png: tblredentry.ps
	echo '(5) false true' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl1redd.png: tblredentry.ps
	echo '(1) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl2redd.png: tblredentry.ps
	echo '(2) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl3redd.png: tblredentry.ps
	echo '(3) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl4redd.png: tblredentry.ps
	echo '(4) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl5redd.png: tblredentry.ps
	echo '(5) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

tbl6redd.png: tblredentry.ps
	echo '(6) true false' | \
	gs -sDEVICE=bmp16 -sOutputFile=tmp.bmp -g300x300 -r216 \
		-dBATCH -dNOPAUSE -q - $<
	convert -geometry 30x30 -antialias tmp.bmp $@
	rm -f tmp.bmp

clean:
	rm -f *.png
