/*
 * httpd.h: a minimal custom HTTP server designed to serve the
 * pages generated by html.h.
 */

#define HTTPD_AUTH_MAGIC 1
#define HTTPD_AUTH_BASIC 2
#define HTTPD_AUTH_NONE  4

struct httpd_config {
    const char *address;
    int port;
    const char *basicauthdata;
};

void run_httpd(const void *t, int authmask, const struct httpd_config *dcfg,
	       const struct html_config *pcfg);
