all: 4tris 5tris

4tris: ntris.c
	gcc -g -o 4tris ntris.c `gtk-config --cflags --libs`

5tris: ntris.c
	gcc -g -o 5tris ntris.c -DSHAPESET=pentris_shapes \
	`gtk-config --cflags --libs`

clean:
	rm -f *.o 4tris 5tris
