all: 4tris 5tris

4tris: ntris.c ntrisgtk.c
	gcc -Wall -g -o 4tris ntris.c ntrisgtk.c `gtk-config --cflags --libs`

5tris: ntris.c ntrisgtk.c
	gcc -Wall -g -o 5tris ntris.c ntrisgtk.c -DSHAPESET=pentris_shapes \
	`gtk-config --cflags --libs`

clean:
	rm -f *.o 4tris 5tris
