/*
 * cron.c - simple reminder-generating cron job
 */

#include <stdio.h>
#include <assert.h>
#include "caltrap.h"

struct cron_ctx {
    char *cmd, *tfmt, *d1fmt, *t1fmt, *d2fmt, *t2fmt;
    FILE *fp;
};

static void cron_callback(void *vctx, Date d, Time t, char *msg)
{
    struct cron_ctx *ctx = (struct cron_ctx *)vctx;
    char *dfmt, *tfmt;

    if (ctx->fp == NULL) {
        ctx->fp = popen(ctx->cmd, "w");
        if (ctx->fp == NULL)
            fatal(err_cronpipe);

        fprintf(ctx->fp,
                "This is an automated calendar notification"
                " generated by Caltrap.\n"
                "Listing your calendar entries in the next %s,\n"
                "i.e. between %s %s and %s %s:\n\n",
                ctx->tfmt,
                ctx->d1fmt, ctx->t1fmt, ctx->d2fmt, ctx->t2fmt);
    }

    dfmt = format_date_full(d);
    tfmt = format_time(t);
    fprintf(ctx->fp, "%s %s %s\n", dfmt, tfmt, msg);
    sfree(dfmt);
    sfree(tfmt);
}

int caltrap_cron(int nargs, char **args, int nphysargs)
{
    Date d, d2;
    Time t, t2, diff;
    char msg[512];
    struct cron_ctx ctx;

    if (nargs != 2)
	fatal(err_cronargno);
    assert(nargs <= nphysargs);

    diff = parse_time(args[0]);
    if (diff == INVALID_TIME)
        fatal(err_time, args[0]);

    now(&d, &t);

    t2 = t + diff;
    d2 = d + (t2 / 86400);
    t2 %= 86400;

    ctx.fp = NULL;
    ctx.cmd = args[1];
    ctx.tfmt = format_time(diff);
    ctx.d1fmt = format_date_full(d);
    ctx.t1fmt = format_time(t);
    ctx.d2fmt = format_date_full(d2);
    ctx.t2fmt = format_time(t2);

    db_list_entries(d, t, d2, t2, cron_callback, &ctx);

    sfree(ctx.tfmt);
    sfree(ctx.d1fmt);
    sfree(ctx.t1fmt);
    sfree(ctx.d2fmt);
    sfree(ctx.t2fmt);
    if (ctx.fp)
        pclose(ctx.fp);
}
