#!/usr/bin/env perl

$debug = 0;
$debug = 1, shift @ARGV if $ARGV[0] eq "-d";

$sigdir = $ENV{"HOME"} . "/.sigs";
srand(time);
if (defined $ARGV[0] and -f $sigdir."/".$ARGV[0]) {
  $file = $sigdir."/".$ARGV[0];
} else {
  opendir DIR, $sigdir;
  @files = grep { /^[^A-Z.]/ && -f $sigdir."/".$_ } readdir(DIR);
  print STDERR "files are ",join(',',@files),"\n" if $debug;
  closedir DIR;
  $i = int ( (1+$#files) * rand );
  $file = $sigdir."/".$files[$i];
}

print STDERR "file is $file\n" if $debug;

open SIG, $file;
print while <SIG>;
close SIG;
